<a href="https://colab.research.google.com/github/Naushad13b/Machine-Learning/blob/main/04)DataSplitingwithDifferentFormate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

dataset_m = pd.read_csv('abcd.csv')
dataset_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   PM2.5   365 non-null    float64
 1   PM10    365 non-null    float64
 2   NO      365 non-null    float64
 3   NO2     365 non-null    float64
 4   SO2     365 non-null    float64
 5   CO      365 non-null    float64
dtypes: float64(6)
memory usage: 17.2 KB


In [ ]:
dataset_m.head()

PM2.5    PM10     NO    NO2   SO2    CO
0  152.81  322.01  42.96  56.50  5.93  2.37
1  169.87  327.02  71.64  49.40  6.20  2.73
2  206.10  402.67  61.40  52.58  8.29  2.79
3  190.26  360.42  91.92  51.02  7.24  3.03
4  188.83  346.03  52.75  56.52  6.96  2.41

In [ ]:
X = dataset_m.iloc[:, [1,2,3,4,5]].values
Y = dataset_m.iloc[:,0].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [ ]:
X_train

array([[186.14,   5.03,  17.07,  14.16,   0.54],
       [284.21,  51.2 ,  49.12,   5.63,   2.33],
       [133.03,  34.7 ,  41.65,   6.3 ,   1.22],
       ...,
       [ 64.96,   7.27,  26.37,   2.51,   0.39],
       [329.95,  16.14,  73.38,   5.44,   1.79],
       [236.79,  39.76,  59.  ,  13.31,   1.36]])

In [ ]:
Y

array([152.81, 169.87, 206.1 , 190.26, 188.83, 175.93, 105.23,  95.3 ,
       105.12,  75.84,  73.29,  94.1 , 112.16, 157.38, 116.78, 121.87,
       116.79, 124.99,  82.33, 157.3 , 129.47, 130.77, 113.55,  88.84,
        73.43, 109.79, 109.63, 111.65, 100.  , 121.13, 144.33, 154.07,
       180.57, 168.51, 158.36, 146.48,  69.59,  88.57,  79.81,  94.38,
       123.4 , 154.19, 157.86, 148.59, 107.8 ,  65.8 , 118.53, 114.35,
       151.39, 135.44, 105.3 , 107.51, 104.4 , 108.05, 107.45,  87.63,
        65.61,  50.66,  41.25,  47.71,  74.53,  76.82,  87.63,  86.  ,
        85.85,  85.07,  83.21, 108.7 , 149.22, 133.98, 103.51,  74.3 ,
        73.77,  98.57, 127.06, 169.14, 132.9 , 117.83, 105.51, 101.16,
        95.67, 112.84,  85.  ,  81.94,  81.71,  82.68,  95.56,  96.47,
        91.22,  91.12, 101.13,  81.71,  99.05,  82.88,  94.75,  84.68,
        80.51,  98.7 ,  98.33, 117.83,  57.51,  79.23,  90.73, 101.65,
        99.3 ,  89.41,  76.95,  51.59,  81.41, 104.17, 116.16,  67.04,
      

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

mlr = LinearRegression()
sc_x = StandardScaler()
X_new_train = sc_x.fit_transform(X_train)

In [ ]:
X_new_train

array([[ 0.36580934, -0.71536182, -0.78098754,  1.65847505, -0.78919114],
       [ 1.38391641,  1.86254392,  0.75638626, -0.24062173,  2.00315432],
       [-0.18554853,  0.94126506,  0.39806544, -0.09145469,  0.27158814],
       ...,
       [-0.89221263, -0.59029123, -0.33488532, -0.93525032, -1.02318657],
       [ 1.85876312, -0.09503406,  1.92008948, -0.28292283,  1.16077077],
       [ 0.89162889,  1.22379058,  1.23030991,  1.46923328,  0.48998387]])

In [ ]:
mlr.fit(X_new_train,y_train)
y_hat = mlr.predict(X_new_train)

In [ ]:
mlr.score(X_test,y_test)

-22721.53618849853